import {spawn} from 'node:child_process';
import {readFile,mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve('.'),target=resolve('tests/artifacts/desktop-native');
await mkdir(target,{recursive:true});
const windows=process.platform==='win32';
const bin=windows?resolve('builds/windows/win-unpacked/Paradise.exe'):resolve('node_modules/electron/dist/electron');
assert(existsSync(bin),'Compile o aplicativo Windows antes do teste; em Linux instale Electron.');
const args=windows?['--disable-gpu','--disable-dev-shm-usage']:['.','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--ozone-platform=headless'];
const child=spawn(bin,args,{cwd:root,env:{...process.env,PARADISE_SMOKE_TEST:target,PARADISE_DATA_DIR:resolve(target,'userdata'),XDG_CACHE_HOME:resolve('.cache/xdg')},stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',s=>output+=s);child.stderr.on('data',s=>output+=s);
const timer=setTimeout(()=>child.kill(),30000);
const exitCode=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('exit',resolve);});clearTimeout(timer);
assert.equal(exitCode,0,output.slice(-5000));
const report=JSON.parse(await readFile(resolve(target,'desktop-smoke.json'),'utf8'));
assert.equal(report.initialView,'title');assert.equal(report.view,'pause');assert.equal(report.dialogues,19);
assert(report.movement>10&&report.paused&&(report.fullscreen||report.headless)&&report.fontLoaded&&report.brandLoaded&&!report.nodeExposed);
console.log(`${windows?'Windows empacotado: marca, fonte, 19 falas, movimento, pausa e tela cheia passaram.':'Electron Linux sem monitor: marca, fonte, 19 falas, movimento e pausa passaram; fullscreen nativo exige display.'}`);
