import {GameEngine} from './game/engine.js';
import {Renderer} from './render/renderer.js';
import {buildWorld} from './world/world.js';
import {BIOMES,BOSSES,ITEMS,WEAPONS,DIALOGUES,MEMORIES,REVELATION} from './data/content.js';
import {TouchControls} from './ui/touch-controls.js';
import {icon} from './ui/icons.js';
import {AudioManager} from './audio/audio.js';
import {esc,makePanel,objective,paintMap,paintPortrait} from './ui/panels.js';

const $=id=>document.getElementById(id),canvas=$('world'),overlay=$('overlay'),hud=$('hud');
const engine=new GameEngine(),renderer=new Renderer(canvas),audio=new AudioManager();
const touch=new TouchControls($('touch-layer'));
for(const [action,id] of [['map','map'],['inventory','bag'],['pause','pause']])hud.querySelector(`[data-action="${action}"]`).innerHTML=icon(id);for(const id of ['fruit','water','heal','camp'])hud.querySelector(`[data-action="${id==='fruit'?'eat':id==='water'?'drink':id}"] span`).innerHTML=icon(id);
const SAVE_KEY='paradise.campanha.v1',BACKUP_KEY='paradise.campanha.backup.v1',SETTINGS_KEY='paradise.configuracoes.v1';
const defaults={volume:.55,muted:false,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches};
let settings={...defaults};try{settings={...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};}catch{}
settings.volume=Math.max(0,Math.min(1,Number(settings.volume)||0));audio.setVolume(settings.volume);audio.setMuted(settings.muted);document.body.classList.toggle('reduced-motion',settings.reducedMotion);
let view={kind:'title'},previousView=null,dialogue=null,endingIndex=0,replay=null,started=false,lastTime=0,hudCounter=0,saveTime=0;
let eventQueue=[],keys=new Set(),pressed=new Set(),mouse={x:320,y:180,time:-10000,left:false,right:false};
let lastGamepadButtons=[],gamepadMenuTimer=0,autoSaveElapsed=0;
let cachedSave=null;try{cachedSave=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{}
engine.start('normal');engine.drainEvents();
// The initial scene is the same garden used by the opening and the final encounter.
const openingScene=structuredClone(engine.state);

function toast(text){if(touch.enabled)text=text.replace('inventário [I]','menu da mochila').replace('poção ácida [R]','poção ácida').replace('com [C]','com o botão Campo elétrico');const el=document.createElement('div');el.className='toast';el.textContent=text;$('toasts').append(el);setTimeout(()=>el.remove(),4200);while($('toasts').children.length>(view&&!['title','dialogue','ending'].includes(view.kind)?1:4))$('toasts').firstChild.remove();}
function applySettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{toast('As configurações serão usadas nesta sessão.');}audio.setVolume(settings.volume);audio.setMuted(settings.muted);document.body.classList.toggle('reduced-motion',settings.reducedMotion);}
function saveGame(){if(!started)return false;try{const snapshot=engine.serialize(),serialized=JSON.stringify(snapshot),old=localStorage.getItem(SAVE_KEY);try{localStorage.setItem(SAVE_KEY,serialized);}catch{localStorage.removeItem(BACKUP_KEY);localStorage.setItem(SAVE_KEY,serialized);}if(old){try{localStorage.setItem(BACKUP_KEY,old);}catch{localStorage.removeItem(BACKUP_KEY);}}cachedSave=snapshot;saveTime=performance.now();$('save-indicator').textContent='✧ Jornada salva';return true;}catch{toast('Não foi possível gravar neste navegador. Exporte o salvamento pelo menu de pausa.');return false;}}
function showTitle(){view={kind:'title'};started=false;dialogue=null;replay=null;eventQueue=[];keys.clear();pressed.clear();audio.stop();hud.classList.add('hidden');renderView();}
function setView(next){view=next;keys.clear();pressed.clear();mouse.left=false;mouse.right=false;touch.reset();if(next){engine.strongHeld=false;if(engine.state?.player)engine.state.player.charge=0;audio.stop();if(!['dialogue','ending','title'].includes(next.kind))$('toasts').innerHTML='';}renderView();}
function closeView(){if(view?.kind==='title')return;if(view?.kind==='dialogue'){advanceDialogue();return;}if(view?.kind==='ending'){advanceEnding();return;}if(previousView){const next=previousView;previousView=null;setView(next);return;}if(!started){showTitle();return;}setView(null);pumpEvents();}
function openPanel(kind,tab){if(view?.kind==='dialogue'||view?.kind==='ending')return;previousView=null;setView({kind,tab});}
function titleMarkup(){const has=!!cachedSave;return `<section class="title-screen" aria-label="Menu inicial"><div class="title-content"><span class="eyebrow">UMA JORNADA ALÉM DA MEMÓRIA</span><h1>PARADISE<span>?</span></h1><div class="title-line"></div><p>Um novo mundo.<br>Um começo esquecido.</p><nav class="title-menu">${has?'<button class="primary" data-action="continue">Continuar jornada <span>→</span></button>':''}<button class="${has?'':'primary'}" data-action="new">Nova jornada <span>→</span></button><button data-action="settings">Configurações <span>◇</span></button><button data-action="controls">Como jogar <span>✧</span></button>${has?'':'<button data-action="import">Importar jornada <span>↑</span></button>'}${window.ParadiseNative||window.ParadiseDesktop?'<button data-action="quit">Sair <span>×</span></button>':''}</nav></div><div class="title-location"><small>O PRIMEIRO PASSO</small><b>Jardins Celestes</b></div><div class="title-footer"><span>EXPLORAR · SOBREVIVER · DESCOBRIR</span><span>${touch.enabled?'TOQUE / GAMEPAD':'TECLADO + MOUSE / GAMEPAD'}</span></div></section>`;}
function renderView(){overlay.className='overlay'+(view&& !['title','dialogue','ending'].includes(view.kind)?' backdrop':'');if(!view){overlay.innerHTML='';return;}if(view.kind==='title'){overlay.innerHTML=titleMarkup();queueMicrotask(()=>overlay.querySelector('button')?.focus({preventScroll:true}));return;}if(view.kind==='dialogue'){const entry=dialogue.lines[dialogue.index];overlay.innerHTML=`<section class="dialogue" role="dialog" aria-label="Conversa com ${esc(entry.speaker)}"><canvas id="portrait" width="48" height="48" class="portrait"></canvas><div class="speech"><span class="speaker">${esc(entry.speaker)}</span><p>${esc(entry.text)}</p><div class="dialogue-footer"><span>${dialogue.index+1} / ${dialogue.lines.length}</span><button class="dialogue-next" data-action="next">${dialogue.index===dialogue.lines.length-1?'Seguir caminho':'Continuar'} &nbsp; → &nbsp; <span>${touch.enabled?'TOQUE':'[ E ]'}</span></button></div></div></section>`;paintPortrait($('portrait'),entry.speaker);return;}if(view.kind==='ending'){renderEnding();return;}overlay.innerHTML=makePanel(view,{state:engine.state,world:engine.world,settings,hasSave:!!cachedSave,touchEnabled:touch.enabled});if(view.kind==='map')paintMap($('region-map'),engine.state,engine.world);queueMicrotask(()=>overlay.querySelector('button:not([disabled])')?.focus({preventScroll:true}));}
function showDialogue(id){const lines=id==='riftComplete'?DIALOGUES[id].filter(l=>l.speaker==='Viajante'):DIALOGUES[id];if(!lines){engine.act('dialogueEnd',id);return;}dialogue={id,lines,index:0};setView({kind:'dialogue'});}
function advanceDialogue(){if(!dialogue)return;keys.clear();pressed.clear();audio.play('ui');if(++dialogue.index<dialogue.lines.length){renderView();return;}const id=dialogue.id;dialogue=null;view=null;engine.act('dialogueEnd',id);processEvents();renderView();pumpEvents();}
function startGame(difficulty){engine.start(difficulty);started=true;view=null;previousView=null;replay=null;eventQueue=[];autoSaveElapsed=0;hud.classList.remove('hidden');audio.unlock();processEvents();saveGame();updateHud();}
function continueGame(snapshot=cachedSave){if(!snapshot||!engine.load(snapshot)){toast('Este salvamento não pôde ser carregado. Você pode importar um backup ou iniciar uma nova jornada.');return false;}started=true;view=null;previousView=null;dialogue=null;eventQueue=[];replay=null;hud.classList.remove('hidden');audio.unlock();processEvents();if(engine.state.phase==='finished'){eventQueue=[];endingIndex=REVELATION.length-1;hud.classList.add('hidden');setView({kind:'ending'});}else if(engine.state.phase==='ending'||engine.state.riftClosed)beginEnding();else if(!engine.state.tutorial?.opening)showDialogue('opening');else if(!engine.state.tutorial?.guide)showDialogue('guide');renderView();updateHud();return true;}
function processEvents(){for(const ev of engine.drainEvents()){if(ev.type==='toast')toast(ev.text);else if(ev.type==='sound')audio.play(({bow:'attack',defeat:'hit',bossDefeat:'boss',acid:'electric',consume:'heal',respawn:'death'})[ev.id]||ev.id||ev.name||ev.sound);else if(ev.type==='save')saveGame();else if(ev.type==='memory'){const text=MEMORIES[(ev.index||0)%MEMORIES.length];$('memory').classList.remove('hidden');$('memory').querySelector('span').textContent=text;audio.play('memory');setTimeout(()=>$('memory').classList.add('hidden'),settings.reducedMotion?1500:2700);}else if(['dialogue','panel','ending'].includes(ev.type))eventQueue.push(ev);}pumpEvents();}
function pumpEvents(){if(view||!eventQueue.length)return;const ev=eventQueue.shift();if(ev.type==='dialogue')showDialogue(ev.id);else if(ev.type==='panel')setView({kind:ev.panel||'support',tab:ev.tab});else if(ev.type==='ending')beginEnding();}
function beginEnding(){eventQueue=[];$('toasts').innerHTML='';$('memory').classList.add('hidden');endingIndex=0;hud.classList.add('hidden');setView({kind:'ending'});audio.play('ending');}
function chooseReplay(visual){if(visual==='opening'||visual==='erase')return {state:structuredClone(openingScene),world:buildWorld(0)};const kinds={bosses:'boss',acid:'acid',electric:'electric',rift:'rift',respawn:'death',survival:'survival'};const records=engine.state.memoryEvents||[];const matches=records.filter(e=>e.kind===kinds[visual]&&e.snapshot);const event=matches.length?matches[visual==='bosses'?endingIndex%matches.length:matches.length-1]:null;if(event){const state={...engine.state,...event.snapshot,biome:event.biome};return {state,world:buildWorld(event.biome)};}return {state:engine.state,world:engine.world};}
function renderEnding(){const entry=REVELATION[endingIndex];replay=chooseReplay(entry.visual);const last=endingIndex===REVELATION.length-1;const intro=endingIndex<3;overlay.innerHTML=`${entry.visual==='erase'?'<div class="end-erase"></div>':''}<section class="ending-screen"><span class="eyebrow">${esc(entry.speaker).toUpperCase()}</span><p>${esc(entry.text)}</p>${last?'':`<button data-action="endingNext">${intro?'Continuar':'Lembrar'} &nbsp; →</button><small>${touch.enabled?'TOQUE PARA CONTINUAR':'E / A · CONTINUAR'}</small>`}</section>`;if(last){$('toasts').innerHTML='';$('memory').classList.add('hidden');engine.act('finish');saveGame();keys.clear();pressed.clear();audio.stop();}}
function advanceEnding(){if(endingIndex>=REVELATION.length-1)return;endingIndex++;if(REVELATION[endingIndex].visual==='electric')audio.play('electric');else audio.play('memory');renderEnding();}
function action(name,value){audio.unlock();if(name==='next'){advanceDialogue();return;}if(name==='endingNext'){advanceEnding();return;}if(name==='close'){closeView();return;}if(name==='new'){setView({kind:'new'});return;}if(name==='start'){startGame(value||'normal');return;}if(name==='continue'){continueGame();return;}if(name==='title'){showTitle();return;}if(name==='quit'){saveGame();if(window.ParadiseNative?.exitGame)window.ParadiseNative.exitGame();else window.ParadiseDesktop?.exitGame();return;}if(name==='returnTitle'){setView({kind:'confirmTitle'});return;}if(name==='tab'){view.tab=value;renderView();return;}if(['inventory','journal','map','pause'].includes(name)){openPanel(name);return;}if(['settings','controls'].includes(name)){if(view?.kind==='pause'||view?.kind==='settings')previousView={...view};setView({kind:name});return;}if(name==='fullscreen'){if(window.ParadiseNative?.fullscreen){window.ParadiseNative.fullscreen();return;}if(!document.fullscreenElement)$('game').requestFullscreen?.().catch(()=>toast('A tela cheia não está disponível neste navegador.'));else document.exitFullscreen?.();return;}if(name==='save'){if(Math.hypot(engine.state.player.x-engine.world.support.x,engine.state.player.y-engine.world.support.y)<65){saveGame();toast('Jornada salva neste ponto de apoio.');}else toast('Visite um ponto de apoio para salvar manualmente.');return;}if(name==='export'){const json=JSON.stringify(engine.serialize(),null,2);if(window.ParadiseNative?.exportSave){window.ParadiseNative.exportSave(json);return;}if(window.ParadiseDesktop?.exportSave){window.ParadiseDesktop.exportSave(json).then(result=>{if(result.ok)toast('Jornada exportada.');else if(!result.cancelled)toast('Não foi possível exportar a jornada.');});return;}const blob=new Blob([JSON.stringify(engine.serialize(),null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='Paradise-jornada.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast('Salvamento exportado. Guarde este arquivo como backup.');return;}if(name==='import'){$('import-save').click();return;}
let payload=value;if(name==='travel')payload=Number(value);if(name==='deposit'||name==='withdraw')payload={item:value,quantity:10};if(name==='weaponUpgrade'){name='upgrade';payload=value;}if(['eat','drink','heal','camp','sleep','repair'].includes(name))payload=undefined;const wasView=view;const ok=engine.act(name,payload);processEvents();updateHud();if(name==='travel'&&ok){previousView=null;setView(null);pumpEvents();}else if(name==='camp'&&ok){setView(null);pumpEvents();}else if(wasView&&view&&view.kind===wasView.kind)renderView();}
overlay.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)action(b.dataset.action,b.dataset.value);});hud.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action,b.dataset.value);});
overlay.addEventListener('input',e=>{if(e.target.id==='setting-volume'){settings.volume=Number(e.target.value)/100;applySettings();}if(e.target.id==='setting-audio'){settings.muted=!e.target.checked;applySettings();}if(e.target.id==='setting-motion'){settings.reducedMotion=e.target.checked;applySettings();}});
$('import-save').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>8*1024*1024)throw Error('size');const state=JSON.parse(await f.text());if(continueGame(state)){saveGame();if(view?.kind!=='ending')toast('Jornada importada. Bom retorno aos jardins.');}}catch{toast('Arquivo inválido. Escolha um salvamento JSON exportado pelo jogo.');}e.target.value='';});
window.addEventListener('paradise-pause',()=>{touch.reset();keys.clear();pressed.clear();mouse.right=false;mouse.left=false;if(started){saveGame();if(!view)openPanel('pause');}});
window.addEventListener('paradise-back',()=>{if(view?.kind==='title')return;if(view)closeView();else openPanel('pause');});
window.addEventListener('paradise-file-result',event=>toast(event.detail?.ok?'Jornada exportada.':'Não foi possível exportar a jornada.'));
const blocked=['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];
window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(blocked.includes(e.code)&&(!view||e.code==='Space'))e.preventDefault();audio.unlock();if(e.repeat)return;keys.add(e.code);pressed.add(e.code);if(view?.kind==='dialogue'){if(['KeyE','Enter','Space'].includes(e.code))advanceDialogue();return;}if(view?.kind==='ending'){if(['KeyE','Enter','Space'].includes(e.code))advanceEnding();return;}if(e.code==='Escape'){if(view)closeView();else openPanel('pause');return;}if(view){if(['ArrowDown','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();const buttons=[...overlay.querySelectorAll('button:not([disabled])')];if(buttons.length){const index=buttons.indexOf(document.activeElement),step=['ArrowUp','ArrowLeft'].includes(e.code)?-1:1;buttons[(index+step+buttons.length)%buttons.length].focus();}}else if(e.code==='Enter')overlay.querySelector('button:focus')?.click();return;}const panels={KeyI:'inventory',KeyB:'inventory',KeyM:'map',KeyN:'journal'};if(panels[e.code]){openPanel(panels[e.code],e.code==='KeyB'?'craft':undefined);return;}const quick={Digit1:'eat',Digit2:'drink',Digit3:'heal',Digit4:'camp'};if(quick[e.code])action(quick[e.code]);});
window.addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*canvas.width;mouse.y=(e.clientY-r.top)/r.height*canvas.height;mouse.time=performance.now();});
canvas.addEventListener('pointerdown',e=>{audio.unlock();if(view)return;canvas.setPointerCapture(e.pointerId);if(e.button===0){pressed.add('MouseLeft');mouse.left=true;}if(e.button===2)mouse.right=true;mouse.time=performance.now();});
window.addEventListener('pointerup',e=>{if(e.button===0)mouse.left=false;if(e.button===2)mouse.right=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('blur',()=>{keys.clear();pressed.clear();mouse.right=false;mouse.left=false;if(started&&!view)openPanel('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!view)openPanel('pause');});window.addEventListener('beforeunload',()=>{if(started&&engine.state.phase!=='finished')saveGame();});
function gamepadInput(dt){const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(!pad){lastGamepadButtons=[];return {};}const down=i=>!!pad.buttons[i]?.pressed,rise=i=>down(i)&&!lastGamepadButtons[i];const moving=v=>Math.abs(v)>.18?v:0;let x=moving(pad.axes[0]||0),y=moving(pad.axes[1]||0),ax=moving(pad.axes[2]||0),ay=moving(pad.axes[3]||0);if(rise(9)){if(view&&view.kind!=='title')closeView();else if(started)openPanel('pause');}if(view?.kind==='dialogue'){if(rise(0)||rise(2))advanceDialogue();}else if(view?.kind==='ending'){if(rise(0))advanceEnding();}else if(view){gamepadMenuTimer-=dt;if(rise(1)&&view.kind!=='title')closeView();if((Math.abs(y)>.4||down(12)||down(13))&&gamepadMenuTimer<=0){const buttons=[...overlay.querySelectorAll('button:not([disabled])')];if(buttons.length){let index=buttons.indexOf(document.activeElement);index=(index+(y<-.4||down(12)?-1:1)+buttons.length)%buttons.length;buttons[index].focus();gamepadMenuTimer=.2;}}if(rise(0)){const target=overlay.querySelector('button:focus')||overlay.querySelector('button');target?.click();}}else{if(rise(8))openPanel('inventory');if(rise(12))action('heal');if(rise(15))action('drink');if(rise(14))action('eat');if(rise(13))pressed.add('KeyR');if(rise(5))pressed.add('KeyC');}
const input={moveX:x,moveY:y,attack:rise(0),dodge:rise(1),interact:rise(2),strong:down(3),sprint:down(7),cycleTarget:rise(4)};if(Math.hypot(ax,ay)>.2){input.aimX=engine.state.player.x+ax*150;input.aimY=engine.state.player.y+ay*150;}lastGamepadButtons=pad.buttons.map(b=>b.pressed);return input;}
function makeInput(pad,touchInput={}){const mx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),my=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);const input={moveX:mx||touchInput.moveX||pad.moveX||0,moveY:my||touchInput.moveY||pad.moveY||0,attack:pressed.has('KeyJ')||pressed.has('MouseLeft')||pad.attack||touchInput.attack,strong:keys.has('KeyF')||mouse.right||pad.strong||touchInput.strong,dodge:pressed.has('Space')||pad.dodge||touchInput.dodge,sprint:keys.has('ShiftLeft')||keys.has('ShiftRight')||pad.sprint||touchInput.sprint,interact:pressed.has('KeyE')||pad.interact||touchInput.interact,cycleTarget:pressed.has('Tab')||pad.cycleTarget||touchInput.cycleTarget,potion:pressed.has('KeyR')||touchInput.potion,electric:pressed.has('KeyC')||touchInput.electric};if(pad.aimX!==undefined){input.aimX=pad.aimX;input.aimY=pad.aimY;}else if(performance.now()-mouse.time<1700){const p=renderer.screenToWorld(mouse.x,mouse.y);input.aimX=p.x;input.aimY=p.y;}return input;}
function updateHud(){const s=engine.state,p=s.player,b=BIOMES[s.biome];$('health-number').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('health-fill').style.width=`${Math.max(0,p.hp/p.maxHp*100)}%`;for(const k of ['hunger','thirst','sleep'])$(k).value=p[k];$('stamina').max=p.maxStamina;$('stamina').value=p.stamina;$('biome-name').textContent=b.name;$('biome-subtitle').textContent=b.subtitle;$('region-counter').textContent=`REGIÃO ${['I','II','III','IV','V','VI','VII','VIII','IX','X'][s.biome]}`;const total=(s.worldTime||0)/780,day=Math.floor(total)+1,hour=((total%1)*24+8)%24;$('clock-time').textContent=`${String(Math.floor(hour)).padStart(2,'0')}:${String(Math.floor(hour%1*60)).padStart(2,'0')}`;$('day-number').textContent=`DIA ${day}`;$('day-icon').textContent=hour>=6&&hour<19?'☀':'☾';if(performance.now()-saveTime>4000)$('save-indicator').textContent='';$('weapon-name').textContent=WEAPONS[p.weapon]?.name||'Sem arma';const weaponEl=hud.querySelector('.weapon-icon');if(weaponEl.dataset.weapon!==String(p.weapon)){weaponEl.innerHTML=icon(p.weapon||'sword');weaponEl.dataset.weapon=String(p.weapon);}const equipment=p.equipment?.[p.weapon];$('weapon-durability').textContent=equipment?`${Math.round(equipment.durability/(equipment.maxDurability||WEAPONS[p.weapon]?.durability||130)*100)}% de condição${equipment.durability<=0?' · quebrada':''}`:'Fabrique uma arma';for(const id of ['fruit','water','heal','camp'])$(id+'-count').textContent=s.inventory[id]||0;$('objective-short').textContent=objective(s);$('boss-hud').classList.toggle('hidden',!s.boss);if(s.boss){$('boss-name').textContent=BOSSES[s.boss.id].name;$('boss-fill').style.width=`${Math.max(0,s.boss.hp/(s.boss.maxHp||BOSSES[s.boss.id].hp)*100)}%`;}
let hint='';const near=o=>Math.hypot(o.x-p.x,o.y-p.y)<42;if(near(engine.world.support))hint='Descansar e preparar';else if(engine.world.npcs?.some(near))hint='Conversar';else if(engine.world.ingredient&&!s.ingredients.includes(engine.world.ingredient.id)&&near(engine.world.ingredient))hint='Colher ingrediente';else if(engine.world.bosses.some(o=>!s.defeated.includes(o.id)&&Math.hypot(o.x-p.x,o.y-p.y)<90))hint='Enfrentar grande invasor';else if((s.camps[s.biome]||[]).some(near))hint='Dormir no acampamento';else if(engine.world.objects.some(o=>o.resource&&near(o)&&!(s.collected?.[s.biome]?.[o.id] !== undefined)))hint='Coletar recurso';else if(near(engine.world.exit))hint='Seguir para a próxima região';if(s.electricUnlocked&&!s.riftClosed&&engine.world.riftNodes?.some(near))hint=touch.enabled?'Ativar o campo elétrico':'C · Ativar campo elétrico';if(s.boss?.id===19&&!s.boss.acidApplied&&s.boss.hp<=s.boss.maxHp*.34)hint=touch.enabled?'Usar a poção ácida':'R · Usar a poção ácida';$('interact-hint').classList.toggle('hidden',!hint||!!view);$('interact-hint').querySelector('span').textContent=hint;}
function frame(time){const dt=Math.min(.05,(time-lastTime)/1000||.016);lastTime=time;const pad=gamepadInput(dt);touch.update(engine.state,view,started);if(started&&!view&&!touch.portrait){engine.update(dt,makeInput(pad,touch.read()));audio.update(engine.state,dt);autoSaveElapsed+=dt;if(autoSaveElapsed>=60){saveGame();autoSaveElapsed=0;}processEvents();}pressed.clear();hudCounter+=dt;if(hudCounter>.08){if(started)updateHud();hudCounter=0;}const drawState=view?.kind==='title'||!started?openingScene:replay?.state||engine.state;const drawWorld=view?.kind==='title'||!started?buildWorldCache:replay?.world||engine.world;renderer.draw({...drawState,touchControls:touch.enabled,cinematic:['title','dialogue','ending'].includes(view?.kind)},drawWorld,view?.kind==='title'?time/1000:drawState.elapsed||0);requestAnimationFrame(frame);}
const buildWorldCache=buildWorld(0);
renderView();requestAnimationFrame(frame);
// Read-only access is useful for browser inspection and integration tests.
window.paradise={get state(){return engine.state;},get view(){return view?.kind||'playing';},get world(){return engine.world;}};
